"use client";

import { useState, useEffect } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { api } from "@/lib/api";
import { formatINR } from "@/lib/format";
import { useToast } from "@/lib/contexts/ToastContext";

export default function AdminFinancePage() {
  const { toast } = useToast();
  const [stats, setStats] = useState<any>(null);
  const [commissionRate, setCommissionRate] = useState<number>(12.0);
  const [newRate, setNewRate] = useState<string>("12.0");
  const [auditLogs, setAuditLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadData = async () => {
    try {
      setLoading(true);
      const [statsRes, settingsRes, auditRes] = await Promise.all([
        api.getAdminDashboard(),
        api.getFinancialSettings(),
        api.getAuditLogs({ action: "PLATFORM_COMMISSION_UPDATED" }),
      ]);

      if (statsRes.success && statsRes.data) {
        setStats(statsRes.data);
      }

      if (settingsRes.success && settingsRes.data) {
        const rate = settingsRes.data.sellerCommissionRate ?? 12.0;
        setCommissionRate(rate);
        setNewRate(String(rate));
      }

      if (auditRes.success && auditRes.data) {
        setAuditLogs(auditRes.data);
      }
    } catch (err: any) {
      setError(err.message || "Failed to load financial records");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleUpdateCommission = async (e: React.FormEvent) => {
    e.preventDefault();
    const parsedRate = parseFloat(newRate);
    if (isNaN(parsedRate) || parsedRate < 0 || parsedRate > 50) {
      toast.error("Invalid commission rate", "Please enter a rate between 0.0% and 50.0%.");
      return;
    }

    try {
      setUpdating(true);
      const res = await api.updateFinancialSettings({ sellerCommissionRate: parsedRate });
      if (res.success) {
        toast.success("Commission rate updated", `Platform rate updated to ${parsedRate}%.`);
        await loadData();
      } else {
        toast.error("Unable to update rate", res.error?.message || "Failed to update commission rate.");
      }
    } catch (err: any) {
      toast.error("Error updating rate", err.message || "An unexpected error occurred.");
    } finally {
      setUpdating(false);
    }
  };

  const gmv = stats?.platform?.totalOrderValue ?? 0;
  const platformRevenue = stats?.platform?.platformRevenue ?? 0;
  const sellerEarnings = gmv - platformRevenue;

  // State for live pricing simulator
  const [simBasePrice, setSimBasePrice] = useState<number>(499);

  // Live simulation calculations (using active commission setting)
  const simCommissionPaise = Math.round(simBasePrice * (commissionRate / 100));
  const simNurseryNet = simBasePrice - simCommissionPaise;
  const simCustomerPrice = simBasePrice;

  return (
    <AdminShell>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-5 rounded border border-[#E2E8F0] shadow-xs">
          <div>
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <h1 className="font-sans text-xl font-bold text-[#0F172A] tracking-tight">Financial & Commission Governance</h1>
            </div>
            <p className="text-xs text-slate-500 mt-1">Configure active platform commission, inspect revenue models, and audit historical policy transitions.</p>
          </div>
          <span className="font-mono text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 rounded px-3 py-1">
            Active Policy v14
          </span>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded p-4 text-xs font-semibold text-red-700">
            {error}
          </div>
        )}

        {loading ? (
          <div className="py-12 flex justify-center">
            <div className="w-8 h-8 border-2 border-[#1B4D3E] border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <>
            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-white rounded border border-[#E2E8F0] p-4 shadow-xs">
                <p className="font-mono text-[10px] font-bold uppercase tracking-wider text-slate-500">Gross Merchandise Value (GMV)</p>
                <p className="font-mono text-2xl font-bold text-[#0F172A] mt-1">{formatINR(gmv)}</p>
                <p className="text-[11px] text-slate-500 mt-1">Total revenue generated by all marketplace orders.</p>
              </div>

              <div className="bg-white rounded border border-[#E2E8F0] p-4 shadow-xs">
                <p className="font-mono text-[10px] font-bold uppercase tracking-wider text-slate-500">Platform Net Commission Revenue</p>
                <p className="font-mono text-2xl font-bold text-emerald-700 mt-1">{formatINR(platformRevenue)}</p>
                <p className="text-[11px] text-slate-500 mt-1">Platform take-rate (authoritative {commissionRate}%).</p>
              </div>

              <div className="bg-white rounded border border-[#E2E8F0] p-4 shadow-xs">
                <p className="font-mono text-[10px] font-bold uppercase tracking-wider text-slate-500">Nursery Distributed Payouts</p>
                <p className="font-mono text-2xl font-bold text-[#0F172A] mt-1">{formatINR(sellerEarnings)}</p>
                <p className="text-[11px] text-slate-500 mt-1">Net earnings payable to approved botanical sellers.</p>
              </div>
            </div>

            {/* Interactive Pricing Simulator & Commission Form */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Commission Rate Form */}
              <div className="bg-white rounded border border-[#E2E8F0] p-5 shadow-xs space-y-4 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-3 mb-3">
                    <h2 className="font-sans text-xs font-bold uppercase tracking-wider text-[#0F172A]">Platform Commission Policy</h2>
                    <span className="font-mono text-[10px] font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded border border-[#E2E8F0]">
                      Server Authoritative
                    </span>
                  </div>
                  <p className="text-xs text-slate-500">
                    This commission rate is authoritatively applied to all nursery line items during checkout.
                  </p>
                </div>

                <form onSubmit={handleUpdateCommission} className="space-y-4 pt-2">
                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-[#0F172A] mb-1.5 font-sans">
                      Default Nursery Commission Rate (%)
                    </label>
                    <div className="flex gap-2">
                      <div className="relative flex-1">
                        <input
                          type="number"
                          step="0.1"
                          min="0"
                          max="50"
                          value={newRate}
                          onChange={(e) => setNewRate(e.target.value)}
                          className="w-full pl-3 pr-8 py-2 font-mono text-xs rounded border border-[#E2E8F0] focus:outline-none focus:ring-1 focus:ring-[#1B4D3E] focus:border-[#1B4D3E] bg-[#F8FAFC]"
                          placeholder="e.g. 12.0"
                        />
                        <span className="absolute right-3 top-1/2 -translate-y-1/2 font-mono text-xs font-bold text-slate-400">%</span>
                      </div>
                      <button
                        type="submit"
                        disabled={updating}
                        className="px-4 py-2 bg-[#1B4D3E] hover:bg-[#14392E] text-white font-bold text-xs uppercase tracking-wider rounded transition-colors disabled:opacity-50 shadow-xs"
                      >
                        {updating ? "Saving..." : "Update Policy"}
                      </button>
                    </div>
                  </div>
                  <p className="text-[11px] text-slate-400 italic">
                    Note: Rates are bounded between 0.0% and 50.0%. Completed historical orders remain frozen at their snapshot rate.
                  </p>
                </form>
              </div>

              {/* Live Interactive Pricing Simulation */}
              <div className="bg-white rounded border border-[#E2E8F0] p-5 shadow-xs space-y-3">
                <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-2.5">
                  <h2 className="font-sans text-xs font-bold uppercase tracking-wider text-[#0F172A]">Live Pricing Simulation</h2>
                  <span className="font-mono text-[10px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded">
                    Active Formula
                  </span>
                </div>

                <div className="flex items-center justify-between gap-4 pt-1">
                  <label className="text-xs font-semibold text-slate-700">Sample Seller Base Price:</label>
                  <div className="flex items-center gap-1 font-mono text-xs">
                    <span>₹</span>
                    <input
                      type="number"
                      min="50"
                      max="10000"
                      value={simBasePrice}
                      onChange={(e) => setSimBasePrice(Number(e.target.value) || 0)}
                      className="w-24 px-2 py-1 border border-[#E2E8F0] rounded font-mono text-xs font-bold text-right"
                    />
                  </div>
                </div>

                <div className="space-y-1.5 pt-2 border-t border-slate-100 text-xs">
                  <div className="flex justify-between text-slate-600">
                    <span>Nursery Base Price:</span>
                    <span className="font-mono font-bold text-[#0F172A]">₹{simBasePrice}</span>
                  </div>
                  <div className="flex justify-between text-amber-800 bg-amber-50/70 px-2 py-1 rounded">
                    <span>Nursery Net Payout ({100 - commissionRate}%):</span>
                    <span className="font-mono font-bold">₹{simNurseryNet}</span>
                  </div>
                  <div className="flex justify-between text-emerald-800 bg-emerald-50/70 px-2 py-1 rounded">
                    <span>Platform Commission Cut ({commissionRate}%):</span>
                    <span className="font-mono font-bold">₹{simCommissionPaise}</span>
                  </div>
                  <div className="flex justify-between text-[#1B4D3E] font-bold pt-1.5 border-t border-[#E2E8F0]">
                    <span>Customer Selling Price:</span>
                    <span className="font-mono text-sm">₹{simCustomerPrice}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Commission Audit History */}
            <div className="bg-white rounded border border-[#E2E8F0] p-5 shadow-xs space-y-3">
              <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-3">
                <div>
                  <h2 className="font-sans text-xs font-bold uppercase tracking-wider text-[#0F172A]">Commission Rate Adjustment Audit Log</h2>
                  <p className="text-[11px] text-slate-500 mt-0.5">Immutable audit trail of all historical platform commission revisions.</p>
                </div>
                <span className="font-mono text-[10px] font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded border border-[#E2E8F0]">
                  {auditLogs.length} Revisions
                </span>
              </div>

              <div className="border border-[#E2E8F0] rounded overflow-hidden">
                {auditLogs.length === 0 ? (
                  <div className="p-8 text-center text-xs text-slate-500">No historical adjustment logs found.</div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full border-collapse text-left text-xs">
                      <thead>
                        <tr className="bg-slate-50 text-slate-600 font-mono text-[11px] font-bold uppercase tracking-wider border-b border-[#E2E8F0]">
                          <th className="p-3">Adjusted Timestamp</th>
                          <th className="p-3">Actor Admin ID</th>
                          <th className="p-3">Previous Rate</th>
                          <th className="p-3">New Active Rate</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-[#E2E8F0]">
                        {auditLogs.map((log) => (
                          <tr key={log.id} className="hover:bg-[#F8FAFC] transition-colors">
                            <td className="p-3 text-slate-600 font-mono text-[11px]">
                              {new Date(log.created_at).toLocaleString("en-IN", {
                                day: "numeric",
                                month: "short",
                                year: "numeric",
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                            </td>
                            <td className="p-3 font-mono text-[11px] text-slate-500">{log.actor_user_id}</td>
                            <td className="p-3 font-mono font-bold text-slate-500">{(log.metadata?.previousRate ?? 12.0)}%</td>
                            <td className="p-3 font-mono font-bold text-emerald-700">{(log.metadata?.newRate ?? 12.0)}%</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
          </>
        )}
      </div>
    </AdminShell>
  );
}
