"use client";

import { useState, useEffect } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { api } from "@/lib/api";
import { formatINR } from "@/lib/format";
import { useToast } from "@/lib/contexts/ToastContext";

export default function AdminFinancePage() {
  const { toast } = useToast();
  const [stats, setStats] = useState<any>(null);
  const [commissionRate, setCommissionRate] = useState<number>(12.0);
  const [newRate, setNewRate] = useState<string>("12.0");
  const [auditLogs, setAuditLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadData = async () => {
    try {
      setLoading(true);
      const [statsRes, settingsRes, auditRes] = await Promise.all([
        api.getAdminDashboard(),
        api.getFinancialSettings(),
        api.getAuditLogs({ action: "PLATFORM_COMMISSION_UPDATED" }),
      ]);

      if (statsRes.success && statsRes.data) {
        setStats(statsRes.data);
      }

      if (settingsRes.success && settingsRes.data) {
        const rate = settingsRes.data.sellerCommissionRate ?? 12.0;
        setCommissionRate(rate);
        setNewRate(String(rate));
      }

      if (auditRes.success && auditRes.data) {
        setAuditLogs(auditRes.data);
      }
    } catch (err: any) {
      setError(err.message || "Failed to load financial records");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleUpdateCommission = async (e: React.FormEvent) => {
    e.preventDefault();
    const parsedRate = parseFloat(newRate);
    if (isNaN(parsedRate) || parsedRate < 0 || parsedRate > 50) {
      toast.error("Invalid commission rate", "Please enter a rate between 0.0% and 50.0%.");
      return;
    }

    try {
      setUpdating(true);
      const res = await api.updateFinancialSettings({ sellerCommissionRate: parsedRate });
      if (res.success) {
        toast.success("Commission rate updated", `Platform rate updated to ${parsedRate}%.`);
        await loadData();
      } else {
        toast.error("Unable to update rate", res.error?.message || "Failed to update commission rate.");
      }
    } catch (err: any) {
      toast.error("Error updating rate", err.message || "An unexpected error occurred.");
    } finally {
      setUpdating(false);
    }
  };

  const gmv = stats?.platform?.totalOrderValue ?? 0;
  const platformRevenue = stats?.platform?.platformRevenue ?? 0;
  const sellerEarnings = gmv - platformRevenue;

  return (
    <AdminShell>
      <div className="space-y-6">
        <div>
          <h1 className="font-serif text-2xl font-bold text-ink-900 leading-tight">Financial & Commission Management</h1>
          <p className="text-xs text-ink-400 mt-0.5">Track platform Gross Merchandise Value (GMV), distribute seller earnings, and update marketplace commission policy.</p>
        </div>

        {error && (
          <div className="bg-error-50 border border-error-100 rounded-xl p-4 text-xs text-error-700">
            {error}
          </div>
        )}

        {loading ? (
          <div className="py-12 flex justify-center">
            <div className="w-8 h-8 border-2 border-forest-600 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <>
            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-white rounded-xl border border-ink-100 p-5 shadow-xs">
                <p className="text-[10px] font-bold uppercase tracking-wider text-ink-400">Gross Merchandise Value (GMV)</p>
                <p className="text-2xl font-bold text-ink-900 mt-1">{formatINR(gmv)}</p>
                <p className="text-[10px] text-ink-400 mt-1">Total revenue generated by all marketplace orders.</p>
              </div>

              <div className="bg-white rounded-xl border border-ink-100 p-5 shadow-xs">
                <p className="text-[10px] font-bold uppercase tracking-wider text-ink-400">Platform Net Commission Revenue</p>
                <p className="text-2xl font-bold text-forest-800 mt-1">{formatINR(platformRevenue)}</p>
                <p className="text-[10px] text-ink-400 mt-1">Net platform fee cut (currently {commissionRate}%).</p>
              </div>

              <div className="bg-white rounded-xl border border-ink-100 p-5 shadow-xs">
                <p className="text-[10px] font-bold uppercase tracking-wider text-ink-400">Seller Distributed Earnings</p>
                <p className="text-2xl font-bold text-ink-900 mt-1">{formatINR(sellerEarnings)}</p>
                <p className="text-[10px] text-ink-400 mt-1">Total value distributed to partner nurseries.</p>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Commission Rate Form */}
              <div className="bg-white rounded-xl border border-ink-100 p-5 shadow-xs space-y-4">
                <div>
                  <h2 className="text-xs font-bold uppercase tracking-wider text-ink-900">Commission Policy Configuration</h2>
                  <p className="text-[10px] text-ink-400 mt-0.5">Authoritative rate applied server-side to order subtotals.</p>
                </div>

                <form onSubmit={handleUpdateCommission} className="space-y-4 pt-2">
                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-ink-700 mb-1">
                      Nursery Commission Rate (%)
                    </label>
                    <div className="flex gap-2">
                      <div className="relative flex-1">
                        <input
                          type="number"
                          step="0.1"
                          value={newRate}
                          onChange={(e) => setNewRate(e.target.value)}
                          className="w-full pl-3 pr-8 py-2 text-xs rounded-lg border border-ink-200 focus:outline-none focus:ring-1 focus:ring-forest-700 bg-white"
                          placeholder="e.g. 12.0"
                        />
                        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-ink-400">%</span>
                      </div>
                      <button
                        type="submit"
                        disabled={updating}
                        className="px-4 py-2 bg-forest-700 hover:bg-forest-800 text-white font-bold text-xs uppercase tracking-wider rounded-lg transition-colors disabled:opacity-50"
                      >
                        Update Rate
                      </button>
                    </div>
                  </div>
                  <p className="text-[10px] text-ink-400 italic">Note: Commission rates are capped between 0.0% and 50.0%. Changing this setting does not retroactively alter completed order commissions.</p>
                </form>
              </div>

              {/* Commission Audit History */}
              <div className="lg:col-span-2 bg-white rounded-xl border border-ink-100 p-5 shadow-xs space-y-4">
                <div>
                  <h2 className="text-xs font-bold uppercase tracking-wider text-ink-900">Commission Rate Adjustment Log</h2>
                  <p className="text-[10px] text-ink-400 mt-0.5">Immutable audit history for policy revisions.</p>
                </div>

                <div className="border border-ink-100 rounded-xl overflow-hidden">
                  {auditLogs.length === 0 ? (
                    <div className="p-8 text-center text-xs text-ink-400">No historical adjustment logs found.</div>
                  ) : (
                    <table className="w-full border-collapse text-left text-xs">
                      <thead>
                        <tr className="bg-cream-100 text-ink-500 font-bold uppercase tracking-wider border-b border-ink-100">
                          <th className="p-3">Adjusted On</th>
                          <th className="p-3">Actor ID</th>
                          <th className="p-3">Previous Rate</th>
                          <th className="p-3">New Rate</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-ink-100">
                        {auditLogs.map((log) => (
                          <tr key={log.id} className="hover:bg-cream-50/50">
                            <td className="p-3 text-ink-600 font-mono text-[10px]">
                              {new Date(log.created_at).toLocaleString()}
                            </td>
                            <td className="p-3 font-mono text-[10px] text-ink-500">{log.actor_user_id}</td>
                            <td className="p-3 font-bold text-ink-600">{(log.metadata?.previousRate ?? 12.0)}%</td>
                            <td className="p-3 font-bold text-forest-700">{(log.metadata?.newRate ?? 12.0)}%</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </AdminShell>
  );
}
