// Floria Icon System — Semantic Taxonomy & Design Tokens

export type FloriaIconName =
  // ── 1. Core Navigation & Discovery ──────────────────────────────────
  | "home"
  | "search"
  | "explore"
  | "categories"
  | "cart"
  | "bag"
  | "favorite"
  | "wishlist"
  | "heart"
  | "orders"
  | "profile"
  | "user"
  | "users"
  // ── 2. Botanical & Marketplace Taxonomy ─────────────────────────────
  | "leaf"
  | "plant"
  | "potted_plant"
  | "flower"
  | "cactus"
  | "tree"
  | "sun"
  | "drop"
  | "water"
  | "sprout"
  | "sparkles"
  | "lightning"
  // ── 3. Actions, Navigation & Controls ───────────────────────────────
  | "plus"
  | "add"
  | "minus"
  | "remove"
  | "close"
  | "x"
  | "menu"
  | "list"
  | "trash"
  | "delete"
  | "edit"
  | "pencil"
  | "share"
  | "thumbs_up"
  | "flag"
  | "filter"
  | "funnel"
  | "sort"
  | "copy"
  | "refresh"
  | "rotate"
  | "history"
  | "camera"
  | "upload"
  | "download"
  | "external_link"
  | "sliders"
  | "eye"
  | "eye_slash"
  | "eye_closed"
  | "check"
  | "arrow_left"
  | "arrow_right"
  | "arrow_up"
  | "arrow_down"
  | "chevron_left"
  | "chevron_right"
  | "chevron_up"
  | "chevron_down"
  | "caret_down"
  | "caret_up"
  // ── 4. Commerce, Payments & Logistics ───────────────────────────────
  | "truck"
  | "delivery"
  | "box"
  | "package"
  | "inbox"
  | "return"
  | "credit_card"
  | "wallet"
  | "bank"
  | "cash"
  | "receipt"
  | "tag"
  | "discount"
  | "clock"
  | "timer"
  | "nursery"
  | "storefront"
  | "store"
  | "star"
  | "star_fill"
  | "shield"
  | "shield_check"
  | "verified"
  | "badge_check"
  | "lock"
  | "logout"
  | "login"
  | "bell"
  | "bell_ringing"
  | "notification"
  | "notifications"
  | "google"
  | "phone"
  | "mail"
  | "location"
  | "map_pin"
  | "navigation"
  | "compass"
  // ── 5. Analytics, Admin & Status Feedback ───────────────────────────
  | "dashboard"
  | "analytics"
  | "chart"
  | "trend_up"
  | "trending_up"
  | "percent"
  | "close_circle"
  | "save"
  | "calendar"
  | "award"
  | "pie_chart"
  | "inventory"
  | "document"
  | "documents"
  | "database"
  | "cpu"
  | "server"
  | "settings"
  | "gavel"
  | "activity"
  | "qr_code"
  | "chat"
  | "question"
  | "help"
  | "info"
  | "warning"
  | "error"
  | "category"
  | "layers"
  | "hard_drive"
  | "user_group"
  | "user_check"
  | "check_circle";

export type FloriaIconWeight =
  | "regular"
  | "fill"
  | "bold"
  | "duotone"
  | "light"
  | "thin";

export type FloriaIconSize = "xs" | "sm" | "md" | "lg" | "xl" | number;

export const ICON_SIZE_MAP: Record<"xs" | "sm" | "md" | "lg" | "xl", number> = {
  xs: 14,
  sm: 18,
  md: 22,
  lg: 26,
  xl: 32,
};

export interface BaseFloriaIconProps {
  name: FloriaIconName;
  size?: FloriaIconSize;
  weight?: FloriaIconWeight;
  color?: string;
  mirrored?: boolean;
  /** Accessible label for screen readers (when icon is interactive or standalone) */
  ariaLabel?: string;
}
